export const PLAY_MUTATION = 'PLAY_MUTATION';
export const NEXT_MUTATION = 'NEXT_MUTATION';
export const PRE_MUTATION = 'PRE_MUTATION';
export const SHOWPLAYER_MUTATION = 'SHOWPLAYER_MUTATION';
export const LOADING_MUTATION = 'LOADING_MUTATION';
